### ISSUE TITLE
java.io.EOFException on case 2 of benchmark

### ISSUE THREAD

**Issue by mbn312** [JoelCourtney/parspice#15]
ParSPICE returns a java.io.EOFException when running a worker that calls System.loadLibrary("JNISpice"). I tried adding the line to the setup of some of the test workers and it also caused them to fail. I'm pretty sure that there is an error when trying to load JNISpice which causes the output to be a null byte, so when it tries to read the output of a certain type, there isn't enough bytes to read leading to the EOFException. Here is the output I get when I try to run the benchmarks.

> Running 6 benchmark jobs. This can take a few minutes.
Running case 0 [output 500 integers]
Running case 1 [square the input]
Running case 2 [gfposc with small step (long)]
OServer thread 0 failed. Check log file 'ParSPICE_worker_log_0.txt for details. If it does not exist, the worker wasn't able to run.
java.io.EOFException
OServer thread 1 failed. Check log file 'ParSPICE_worker_log_1.txt for details. If it does not exist, the worker wasn't able to run.
java.io.EOFException
java.io.EOFException
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3381)
        at java.base/java.io.ObjectInputStream.readInt(ObjectInputStream.java:1113)
        at parspice.sender.DoubleArraySender.read(DoubleArraySender.java:44)
        at parspice.sender.DoubleArraySender.read(DoubleArraySender.java:21)
        at parspice.io.OServer.run(OServer.java:43)
        at java.base/java.lang.Thread.run(Thread.java:831)
java.io.EOFException
        at java.base/java.io.DataInputStream.readInt(DataInputStream.java:398)
        at java.base/java.io.ObjectInputStream$BlockDataInputStream.readInt(ObjectInputStream.java:3381)
        at java.base/java.io.ObjectInputStream.readInt(ObjectInputStream.java:1113)
        at parspice.sender.DoubleArraySender.read(DoubleArraySender.java:44)
        at parspice.sender.DoubleArraySender.read(DoubleArraySender.java:21)
        at parspice.io.OServer.run(OServer.java:43)
        at java.base/java.lang.Thread.run(Thread.java:831)
Exception in thread "main" java.net.BindException: Address already in use
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:552)
        at java.base/sun.nio.ch.Net.bind(Net.java:541)
        at java.base/sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643)
        at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:281)
        at java.base/java.net.ServerSocket.<init>(ServerSocket.java:172)
        at parspice.io.OServer.<init>(OServer.java:26)
        at parspice.worker.Job.runCommon(Job.java:93)
        at parspice.worker.OJob.run(OJob.java:30)
        at parspiceBench.BenchmarkKt.run(Benchmark.kt:51)
        at parspiceBench.BenchmarkKt.main(Benchmark.kt:36)
        at parspiceBench.BenchmarkKt.main(Benchmark.kt)

**Comment by JoelCourtney** [comment]
Hmm. Is there anything in ParSPICE_worker_log_0.txt or ...log_1.txt? We used to have an issue where the worker processes could be left hanging if the main process was killed or crashed; then the next time you run it, you'd get a "Address already in use" error like this. Are there any java processes running in the background (like, right now, not while running the benchmark) that you don't recognize?

**Comment by JoelCourtney** [comment]
Even if you can't find any rogue Java processes, I'd restart your computer just in case. If that fixes the problem, then I'm fairly confident that was the problem.

Also, you could try changing the port number on line 7 of `src/bench/kotlin/parspiceBench/Benchmark.kt` to something else.

**Comment by mbn312** [comment]
I didn't see any rogue Java processes, but I'll try restarting my computer to see if that fixes the problem. Also, here are my worker logs just in case.

[ParSPICE_worker_log_0.txt](https://github.com/JoelCourtney/parspice/files/7810473/ParSPICE_worker_log_0.txt)
[ParSPICE_worker_log_1.txt](https://github.com/JoelCourtney/parspice/files/7810474/ParSPICE_worker_log_1.txt)

**Comment by mbn312** [comment]
Tried restarting and changing the port, but I'm still getting the same errors. Also, I just looked at the logs I sent and realized that they are from when I stopped the benchmark early and not from the Exception that I'm getting, so I guess the workers aren't able to run.

**Comment by mbn312** [comment]
I think I found the problem. It seems like JNISpice is not being added to the jar file correctly. I'll fix this and let you know if this solves the problem.

**Comment by JoelCourtney** [comment]
Oh, I was just about to drop a giant comment :). I'll leave it here for future reference in case that doesn't turn out to be the problem:

---

Ok I'm not sure whats going on here, so I'm just going to throw a bunch of questions at you:

- What operating system are you using? Linux or Mac is ideal. If its a Windows-specific problem, it might be tough to debug because I suck at Windows.
- You said other team members are running into the same problem outside of the benchmark. Does anyone have a minimal failing case, so I can try to reproduce it? The benchmark works fine for me, because I wrote it on this machine, so of course it works :)
- The array of benchmark cases is located on line 20 of `src/bench/kotlin/parspiceBench/Benchmark.kt`. Messing with that array could give us some info on exactly what part is failing.
    - Try deleting `GfposcWorker` from the list and see if something else fails.
    - Try putting it first or last in the list, and make sure its always Gfposc that fails. That may seem unnecessary, but I find it really weird that the same case would fail this way every time, considering that all of the benchmark cases share the same networking code.
- Have you ever successfully run the benchmark? It sounded like you had in your email from November.

**Comment by JoelCourtney** [comment]
There's two different components to JNISpice. There's the Java source code (the actual Java Native Interface stuff), and a compiled C library. Only the Java source code needs to be inside the Jar, and it looks like you did that successfully, otherwise it wouldn't compile.

The compiled library (something like `libJNISpice.jnilib`) is the part that is loaded by `System.loadLibrary`, and the file needs to be placed somewhere in your Java library path. You should find it already compiled in the JNISpice download from NASA/JPL. The Java library path varies between operating systems, so you'll need to look that up yourself.

Edit: `libJNISpice.jnilib` not `libJNISpice.so`

**Comment by mbn312** [comment]
I got it working. Thanks!
